import { LegalPage } from "@/components/LegalPage";
import { legal } from "@/lib/legal";

export default function TermsPage() {
  return <LegalPage title="Terms of Use">
    <section><h2>Agreement and eligibility</h2><p>These Terms are an agreement between you and {legal.entity}. You must be at least {legal.minimumAge}, able to form a binding contract, and provide accurate information. Your use of the service and checked acceptance during registration signify agreement.</p></section>
    <section><h2>Marketplace role</h2><p>We provide technology for customers and independent contractors to find one another, message, exchange quotes, and record project status. We are not a contractor, employer, agent, party to a customer-contractor contract, guarantor, escrow service, lender, merchant of record, or payment processor. Users select each other and remain responsible for due diligence.</p></section>
    <section><h2>Quotes and outside payment</h2><p>An accepted quote records a direct agreement between the customer and contractor. They are responsible for scope, permits, licensing, insurance, taxes, deposits, payment, change orders, cancellation notices, warranties, and state-required written contracts. Payments occur outside the service and are not held, verified, protected, or refunded by us. A “paid outside” marker is a user report only.</p></section>
    <section><h2>User obligations</h2><ul><li>Comply with federal, state, and local law and trade requirements.</li><li>Do not misrepresent identity, credentials, insurance, reviews, or project facts.</li><li>Do not send payment credentials, Social Security numbers, malware, threats, or unlawful content.</li><li>Contractors are solely responsible for workers, taxes, permits, safety, and work quality.</li></ul></section>
    <section><h2>Content, reviews, and enforcement</h2><p>You retain ownership of your content and grant us a license to host and display it to operate the service. Reviews must reflect genuine experiences. We may remove content, suspend accounts, preserve evidence, and cooperate with lawful requests. “Verified” means only the specific check we expressly describe and is not an endorsement.</p></section>
    <section><h2>Disclaimers and liability</h2><p>The service is provided “as is” to the fullest extent allowed by law. We do not guarantee users, quotes, availability, licensing, work, payment, or outcomes. To the fullest lawful extent, our aggregate liability is limited to the greater of $100 or fees you paid us in the prior 12 months. Nothing excludes liability that cannot legally be excluded.</p></section>
    <section><h2>Disputes and governing law</h2><p>Users should first contact {legal.email}. Disputes between customer and contractor are theirs to resolve. These Terms are governed by the laws of {legal.state}, without overriding mandatory consumer protections. Venue lies in the operator’s applicable state or federal courts unless law requires otherwise.</p></section>
    <section><h2>Changes and contact</h2><p>Material changes will require notice or renewed acceptance where appropriate. Contact {legal.entity}, {legal.address}, at {legal.email}.</p></section>
  </LegalPage>;
}
